name: project_prapw
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.4.3
  flutter_svg: ^2.0.9
  mobile_scanner: ^6.0.2
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  flutter_image_compress: ^2.2.0
  provider: ^6.1.5
  fl_chart: 0.63.0
  google_fonts: ^6.3.0
  intl: ^0.20.2
  carousel_slider: ^5.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/